In [62]:
rows = 5
for i in range(0,rows):
    for j in range(3):
        print("*", end=' ')
    print()

* * * 
* * * 
* * * 
* * * 
* * * 


In [1]:
for i in range(1,4):
    for j in range(1,4):
        print(i,j)
    print()
    

1 1
1 2
1 3

2 1
2 2
2 3

3 1
3 2
3 3



In [22]:
rows=2
cols=3
a=[1,2,3]
b=[4,5,6]
for i in range(0,rows):
    for j in range(0,cols):
        b.append(a)   
print(b)


[4, 5, 6, [1, 2, 3], [1, 2, 3], [1, 2, 3], [1, 2, 3], [1, 2, 3], [1, 2, 3]]


In [29]:
import numpy as np
rows=3
cols=3
ar2d = np.zeros((rows,cols), dtype = 'float32')
for i in range(1,rows,2):
    for j in range(1,cols,2):
        ar2d[i,j] = i*j
print(ar2d)

[[0. 0. 0.]
 [0. 1. 0.]
 [0. 0. 0.]]


In [94]:
import numpy as np
m = np.array([[[11,12,13]],[[21,22,23]],[[31,32,33]]])
print(m)

[[[11 12 13]]

 [[21 22 23]]

 [[31 32 33]]]


In [95]:
m.ndim

3

In [96]:
m[0,0,0]

11

In [98]:
m[1,0,1]

22

In [99]:
m[2,0,2]

33

In [110]:
print(m[:,0:2,2])

[[13]
 [23]
 [33]]


In [124]:
import numpy as np
m = np.array([[11,12,13],[21,22,23],[31,32,33]])
print(m)

[[11 12 13]
 [21 22 23]
 [31 32 33]]


In [125]:
m[0,0]

11

In [122]:
m[1,1]

22

In [126]:
m[2,2]

33

In [133]:
m[np.array([0,1,2]), np.array([0,1,2])]

array([11, 22, 33])

In [135]:
m[np.array([0,1,2]), np.array([2,2,2])]

array([13, 23, 33])

In [139]:
m[np.array([0,1]),0:2]

array([[11, 12],
       [21, 22]])

In [145]:
m[np.array([1,2]),1:3]

array([[22, 23],
       [32, 33]])

In [148]:
m[np.array([0,0,1,1]), np.array([0,2,0,2])]

array([11, 13, 21, 23])

In [78]:
import numpy as np
x = np.arange(10)

x[0:-1:2]

array([0, 2, 4, 6, 8])

In [87]:
x = x.reshape(2,5)
x

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [89]:
x[1][3]

8